version: "3.7"
services:
  back-end-php:
    build:
      context: ../
      dockerfile: back-end/Dockerfile.v2
    image: permanent-test
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "2.0"
        reservations:
          cpus: "1.0"
  load_balancer:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      "back-end-php":
        condition: service_started
      stela:
        condition: service_healthy
  stela:
    restart: always
    build:
      context: ../stela
      dockerfile: packages/api/Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ../stela/.env
    volumes:
      - ../stela:/usr/local/apps/stela/
      - ignore_module:/usr/local/apps/stela/node_modules
      - ignore_api:/usr/local/apps/stela/packages/api/node_modules
      - ignore_logger:/usr/local/apps/stela/packages/logger/node_modules
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:8080/api/v2/health
  cache:
    image: memcached:1.5.6-alpine
    ports:
      - "11211:11211"
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: permanent
    healthcheck:
      test: pg_isready
    ports:
      - "5432:5432"
  database_setup:
    image: postgres:14-alpine
    volumes:
      - ../stela/database/base.sql:/base.sql:ro
      - ../back-end/library/db:/db:ro
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "SELECT 'CREATE DATABASE permanent' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'permanent')\gexec" | psql postgresql://postgres:permanent@database:5432
        psql postgresql://postgres:permanent@database:5432/permanent -f /base.sql
        apk add curl
        curl -L -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/download/v1.16.0/dbmate-linux-amd64
        chmod +x /usr/local/bin/dbmate
        (dbmate --url postgresql://postgres:permanent@database:5432/permanent?sslmode=disable up)
    depends_on:
      database:
        condition: service_healthy
volumes:
  ignore_module:
  ignore_api:
  ignore_logger:
#  docker compose up --force-recreate
#  https://local.permanent.org/app
